language: java
sudo: false
dist: trusty
jdk:
  - oraclejdk8
env:
  global:
    - DEPLOY_USERNAME=travis-ci-idm-user-management
    - secure: PxWADglXd2eOJ6YrpuILdlZfW7B3RDIj8hXTfNzk26cojXND/AwqERKXbHXuE0/qjsZ2alLhPsCKFZLyGKeII9pKc1g2q66BqBOV4rN4xioRB27qHoOC/ZPsnF96eyeXIBmF/Lw92xkja4rWOB8e3T7f0+eJBUI4r5wyxlqem4A=
branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2/repository
before_cache:
  - rm -rf $HOME/.m2/repository/org/ccci/gto/idm-user-management*

after_success:
  - mvn jacoco:report coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN

deploy:
  provider: script
  skip_cleanup: true
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -DskipTests=true"
  on:
    repo: CruGlobal/idm-user-management
    branch: master
    jdk: oraclejdk8

notifications:
  email: false
