language: java
sudo: false
jdk:
  - oraclejdk8
branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2/repository

after_success:
  - mvn jacoco:report coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN

notifications:
  email: false
